import { NextRequest } from 'next/server'
import { db } from '@/lib/db'
import { getSession, requireAuth, ok, err } from '@/lib/api-utils'
import { writeAuditLog } from '@/lib/auth'

// POST /api/automation/stale-customer-tasks
// İletişimsiz müşteriler (30+ gün) için otomatik görev oluşturur
export async function POST(req: NextRequest) {
  const user = await getSession(req)
  const authErr = requireAuth(user)
  if (authErr) return authErr

  // Sadece admin veya manager çalıştırabilir
  if (user!.role !== 'admin' && user!.role !== 'manager' && user!.role !== 'superadmin') {
    return err('Bu işlem için yetkiniz yok', 403)
  }

  const url = new URL(req.url)
  const thresholdDays = parseInt(url.searchParams.get('days') || '30')
  const staleDate = new Date()
  staleDate.setDate(staleDate.getDate() - thresholdDays)

  // İletişimsiz müşterileri bul (sahibi olan, threshold gündür iletişimsiz)
  const staleCustomers = await db.customer.findMany({
    where: {
      tenantId: user!.tenantId,
      status: 'aktif',
      ownerId: { not: null },
      OR: [
        { lastActivityAt: { lt: staleDate } },
        { lastActivityAt: null },
      ],
    },
    select: {
      id: true,
      name: true,
      ownerId: true,
      lastActivityAt: true,
    },
    take: 200,
  })

  // Her müşteri için zaten açık otomatik görev var mı kontrol et
  const existingAutoTasks = await db.task.findMany({
    where: {
      tenantId: user!.tenantId,
      status: 'acik',
      autoGenerated: true,
      customerId: { in: staleCustomers.map((c) => c.id) },
    },
    select: { customerId: true },
  })
  const customersWithTask = new Set(existingAutoTasks.map((t) => t.customerId))

  const toCreate = staleCustomers.filter((c) => !customersWithTask.has(c.id))
  const now = new Date()
  const dueDate = new Date(now.getTime() + 3 * 24 * 60 * 60 * 1000) // 3 gün sonrası

  const tasks: { customerId: string; customerName: string }[] = []

  for (const c of toCreate) {
    const days = c.lastActivityAt
      ? Math.floor((now.getTime() - new Date(c.lastActivityAt).getTime()) / (1000 * 60 * 60 * 24))
      : 999

    const task = await db.task.create({
      data: {
        tenantId: user!.tenantId,
        title: `${c.name} ile iletişime geç`,
        description: `Bu müşteri ${days === 999 ? 'hiç' : days + ' gündür'} iletişimsiz. Otomatik oluşturulan görev. Müşteriyle iletişime geçip durum güncellemesi yapın.`,
        dueDate,
        assigneeId: c.ownerId,
        customerId: c.id,
        priority: days > 60 ? 'yuksek' : days > 30 ? 'orta' : 'dusuk',
        reminderTime: '09:00',
        status: 'acik',
        autoGenerated: true,
      },
    })

    tasks.push({ customerId: c.id, customerName: c.name })

    await writeAuditLog({
      tenantId: user!.tenantId,
      actorId: user!.id,
      action: 'create',
      entity: 'task',
      entityId: task.id,
      after: { ...task, source: 'automation_stale_customer' },
    })
  }

  return ok({
    scanned: staleCustomers.length,
    created: tasks.length,
    skipped: customersWithTask.size,
    tasks: tasks.slice(0, 10),
    thresholdDays,
  })
}
