import { NextRequest } from 'next/server'
import { db } from '@/lib/db'
import {
  getSession, requireAuth, ok, err,
  getVisibilityFilter,
} from '@/lib/api-utils'
import { writeAuditLog } from '@/lib/auth'
import { hasPermission } from '@/lib/rbac'

// GET — görev listesi
export async function GET(req: NextRequest) {
  const user = await getSession(req)
  const authErr = requireAuth(user)
  if (authErr) return authErr

  const url = new URL(req.url)
  const status = url.searchParams.get('status') || ''
  const assigneeId = url.searchParams.get('assigneeId') || ''
  const customerId = url.searchParams.get('customerId') || ''
  const priority = url.searchParams.get('priority') || ''
  const overdue = url.searchParams.get('overdue') === 'true'
  const dueToday = url.searchParams.get('dueToday') === 'true'
  const limit = parseInt(url.searchParams.get('limit') || '50')
  const offset = parseInt(url.searchParams.get('offset') || '0')

  const visFilter = await getVisibilityFilter(user!)

  const where: Record<string, unknown> = {
    tenantId: user!.tenantId,
    ...(visFilter.ownerId ? { assigneeId: visFilter.ownerId } : {}),
  }

  if (status) where.status = status
  if (assigneeId) where.assigneeId = assigneeId
  if (customerId) where.customerId = customerId
  if (priority) where.priority = priority

  const now = new Date()
  if (overdue) {
    where.status = 'acik'
    where.dueDate = { lt: now }
  } else if (dueToday) {
    const start = new Date(now)
    start.setHours(0, 0, 0, 0)
    const end = new Date(now)
    end.setHours(23, 59, 59, 999)
    where.dueDate = { gte: start, lte: end }
  }

  const [tasks, total] = await Promise.all([
    db.task.findMany({
      where,
      include: {
        assignee: { select: { id: true, name: true } },
        customer: { select: { id: true, name: true } },
      },
      orderBy: { dueDate: 'asc' },
      take: limit,
      skip: offset,
    }),
    db.task.count({ where }),
  ])

  return ok({ items: tasks, total, limit, offset })
}

// POST — yeni görev
export async function POST(req: NextRequest) {
  const user = await getSession(req)
  const authErr = requireAuth(user)
  if (authErr) return authErr

  const body = await req.json()
  const { title, description, dueDate, assigneeId, customerId, priority, reminderTime } = body

  if (!title) return err('Görev başlığı gerekli', 400)
  if (!dueDate) return err('Bitiş tarihi gerekli', 400)

  const targetAssigneeId = assigneeId || user!.id

  // Yetki: tasks.manage varsa herkese atayabilir; yoksa yalnızca kendine (self-assign)
  const canManage = hasPermission(user!, 'tasks.manage')
  if (!canManage && targetAssigneeId !== user!.id) {
    return err('Yalnızca kendinize görev atayabilirsiniz', 403)
  }

  // Assignee tenant'ta mı?
  if (targetAssigneeId !== user!.id) {
    const assignee = await db.user.findFirst({
      where: { id: targetAssigneeId, tenantId: user!.tenantId },
      select: { id: true },
    })
    if (!assignee) return err('Atanan kullanıcı bulunamadı', 404)
  }

  // Customer tenant'ta mı?
  if (customerId) {
    const cust = await db.customer.findFirst({
      where: { id: customerId, tenantId: user!.tenantId },
      select: { id: true },
    })
    if (!cust) return err('Müşteri bulunamadı', 404)
  }

  const task = await db.task.create({
    data: {
      tenantId: user!.tenantId,
      title,
      description: description || null,
      dueDate: new Date(dueDate),
      assigneeId: targetAssigneeId,
      customerId: customerId || null,
      priority: priority || 'orta',
      reminderTime: reminderTime || null,
      status: 'acik',
      autoGenerated: false,
    },
    include: {
      assignee: { select: { id: true, name: true } },
      customer: { select: { id: true, name: true } },
    },
  })

  await writeAuditLog({
    tenantId: user!.tenantId,
    actorId: user!.id,
    action: 'create',
    entity: 'task',
    entityId: task.id,
    after: task,
  })

  return ok(task, 201)
}


