// GNC CRM — TypeScript Tipleri

export type Role =
  | 'superadmin'
  | 'admin'
  | 'manager'
  | 'rep'
  | 'readonly'
  | 'stock'
  | 'kasa'
  | 'barmen'
  | 'komi'
  | 'kasiyer'
  | 'depo_sorumlusu'

export type PermissionKey =
  | 'customers.view.own'
  | 'customers.view.team'
  | 'customers.view.all'
  | 'customers.edit'
  | 'customers.delete'
  | 'leads.import'
  | 'leads.view'
  | 'leads.edit'
  | 'maps.search'
  | 'deals.manage'
  | 'tasks.manage'
  | 'tasks.view'
  | 'reports.view'
  | 'users.manage'
  | 'roles.manage'
  | 'settings.manage'
  | 'export.data'
  | 'audit.view'
  | 'erp.manage'
  | 'production.view'
  | 'production.manage'
  | 'cafe.view'
  | 'cafe.manage'
  | 'cafe.orders'
  | 'cafe.bar'
  | 'cafe.kitchen'
  | 'market.view'
  | 'market.pos'
  | 'market.stock'
  | 'market.manage'
  | 'site.view'
  | 'site.manage'
  | 'appointments.view'
  | 'appointments.manage'
  | 'expenses.view'
  | 'expenses.manage'
  | 'admin.access'
  | 'dashboard.view'
  | 'messages.view'
  | 'social.view'
  | 'social.manage'
  | 'orders.view'
  | 'irsaliye.view'
  | 'irsaliye.manage'
  | 'invoices.view'
  | 'hr.view'
  | 'hr.manage'
  | 'tickets.view'
  | 'tickets.manage'

export interface SessionUser {
  id: string
  tenantId: string
  email: string
  employeeCode: string | null
  name: string
  role: Role
  permissions: PermissionKey[]
  managerId: string | null
  title: string | null
  phone: string | null
  avatarUrl: string | null
  tenant: {
    id: string
    name: string
    plan: string
    defaultCurrency: string
    country: string
  }
}

export interface Customer {
  id: string
  tenantId: string
  name: string
  sector: string
  segment: string
  ownerId: string | null
  owner?: { id: string; name: string } | null
  source: string
  address: string | null
  city: string | null
  country: string
  lat: number | null
  lng: number | null
  placeId: string | null
  phone: string | null
  email: string | null
  web: string | null
  taxNumber: string | null
  logo: string | null
  customerType: string
  status: string
  tags: string[]
  kvkkConsent: boolean
  kvkkConsentAt: string | null
  annualRevenue: number | null
  employeeCount: number | null
  lastActivityAt: string | null
  createdAt: string
  updatedAt: string
  _count?: {
    contacts: number
    activities: number
    deals: number
    tasks: number
    notes: number
  }
}

export interface Contact {
  id: string
  customerId: string
  name: string
  position: string | null
  email: string | null
  phone: string | null
  photo: string | null
  isPrimary: boolean
  createdAt: string
}

export interface Activity {
  id: string
  customerId: string | null
  leadId: string | null
  dealId: string | null
  type: string
  subject: string
  detail: string | null
  date: string
  durationMin: number
  outcome: string | null
  userId: string | null
  user?: { id: string; name: string } | null
  customer?: { id: string; name: string } | null
  createdAt: string
}

export interface Note {
  id: string
  customerId: string
  userId: string | null
  user?: { id: string; name: string } | null
  content: string
  isPinned: boolean
  createdAt: string
  updatedAt: string
}

export interface Task {
  id: string
  tenantId: string
  title: string
  description: string | null
  dueDate: string
  assigneeId: string | null
  assignee?: { id: string; name: string } | null
  customerId: string | null
  customer?: { id: string; name: string } | null
  priority: string
  reminderTime: string | null
  status: string
  autoGenerated: boolean
  completedAt: string | null
  createdAt: string
}

export interface Deal {
  id: string
  tenantId: string
  title: string
  customerId: string
  customer?: { id: string; name: string }
  value: number
  currency: string
  stage: string
  probability: number
  expectedCloseDate: string | null
  ownerId: string | null
  owner?: { id: string; name: string } | null
  lossReason: string | null
  lossNote: string | null
  createdAt: string
  updatedAt: string
}

export interface Lead {
  id: string
  tenantId: string
  name: string
  placeId: string | null
  category: string | null
  address: string | null
  city: string | null
  country: string
  lat: number | null
  lng: number | null
  phone: string | null
  web: string | null
  email: string | null
  rating: number | null
  reviewCount: number | null
  ownerId: string | null
  owner?: { id: string; name: string } | null
  source: string
  status: string
  convertedCustomerId: string | null
  convertedCustomer?: { id: string; name: string } | null
  notes: string[]
  mapsSearchId: string | null
  createdAt: string
  updatedAt: string
}

export interface MapsSearch {
  id: string
  tenantId: string
  userId: string | null
  user?: { id: string; name: string } | null
  query: string
  city: string | null
  country: string
  radius: number | null
  resultCount: number
  importedCount: number
  createdAt: string
}

export interface MapsResult {
  placeId: string
  name: string
  category: string
  address: string
  city: string
  phone: string | null
  web: string | null
  rating: number | null
  reviewCount: number | null
  lat: number
  lng: number
  existsInCrm: boolean
}

export interface AuditLog {
  id: string
  tenantId: string
  actorId: string | null
  actor?: { id: string; name: string } | null
  action: string
  entity: string
  entityId: string | null
  before: unknown
  after: unknown
  createdAt: string
}

export interface UserListItem {
  id: string
  email: string
  employeeCode: string | null
  name: string
  role: Role
  permissions: PermissionKey[]
  managerId: string | null
  manager?: { id: string; name: string } | null
  status: string
  title: string | null
  phone: string | null
  avatarUrl: string | null
  createdAt: string
  subordinates?: { id: string; name: string; role: Role }[]
  _count?: {
    ownedCustomers: number
    ownedLeads: number
    ownedDeals: number
    subordinates: number
    assignedTasks?: number
    activities?: number
    auditLogs?: number
  }
}
