import { NextRequest } from 'next/server'
import { db } from '@/lib/db'
import { getSession, requireAuth, ok } from '@/lib/api-utils'

// GET — otomasyon ayarlarını ve durumunu getir
export async function GET(req: NextRequest) {
  const user = await getSession(req)
  const authErr = requireAuth(user)
  if (authErr) return authErr

  // Ayarları oku (defaults ile)
  const settingsRows = await db.tenantSetting.findMany({
    where: {
      tenantId: user!.tenantId,
      key: { in: ['automation.enabled', 'automation.thresholdDays'] },
    },
  })
  const settingsMap: Record<string, string> = {
    'automation.enabled': 'true',
    'automation.thresholdDays': '30',
  }
  for (const s of settingsRows) settingsMap[s.key] = s.value

  const enabled = settingsMap['automation.enabled'] !== 'false'
  const thresholdDays = parseInt(settingsMap['automation.thresholdDays'] || '30')

  const staleDate = new Date()
  staleDate.setDate(staleDate.getDate() - thresholdDays)

  const [staleCount, autoTaskCount] = await Promise.all([
    db.customer.count({
      where: {
        tenantId: user!.tenantId,
        status: 'aktif',
        ownerId: { not: null },
        OR: [
          { lastActivityAt: { lt: staleDate } },
          { lastActivityAt: null },
        ],
      },
    }),
    db.task.count({
      where: {
        tenantId: user!.tenantId,
        autoGenerated: true,
        status: 'acik',
      },
    }),
  ])

  return ok({
    staleCustomerCount: staleCount,
    openAutoTaskCount: autoTaskCount,
    thresholdDays,
    enabled,
    lastRun: null,
  })
}
