import { NextRequest } from 'next/server'
import { db } from '@/lib/db'
import { getSession, requireAuth, ok, err } from '@/lib/api-utils'
import { sendMail } from '@/lib/mailer'

// POST /api/automation/membership-reminders
// Bitmek üzere olan aktif üyelikler için hatırlatma üretir:
//  - Takip görevi oluşturur (autoGenerated, status=acik)
//  - Bağlı randevu müşterisinin e-postası varsa SMTP ile e-posta gönderir (best-effort)
//  - remindedAt işaretler → tekrar çalıştırmada aynı üyelik atlanır
// Body: { days?: number (default 3), tenantId?: string (superadmin için) }
export async function POST(req: NextRequest) {
  const user = await getSession(req)
  const authErr = requireAuth(user)
  if (authErr) return authErr

  const body = await req.json().catch(() => ({}))
  const days = Math.min(Math.max(parseInt(String(body?.days ?? '3'), 10) || 3, 1), 30)

  const now = new Date()
  const until = new Date(now.getTime() + days * 24 * 60 * 60 * 1000)

  // Tek üyelik için manuel hatırlatma (UI "Hatırlat" butonu)
  const singleWhere = body?.subscriptionId
    ? { id: String(body.subscriptionId), tenantId: user!.tenantId, status: 'aktif', remindedAt: null }
    : null

  const expiring = await db.memberPackage.findMany({
    where: singleWhere ?? {
      tenantId: user!.tenantId,
      status: 'aktif',
      expiryDate: { gte: now, lte: until },
      remindedAt: null,
    },
    include: {
      package: { select: { name: true, sessionCount: true } },
    },
    orderBy: { expiryDate: 'asc' },
    take: 100,
  })

  if (expiring.length === 0) {
    return ok({ scanned: 0, reminded: 0, emailed: 0, tasksCreated: 0, message: 'Hatırlatılacak üyelik yok' })
  }

  // Bildirim görevi atayacak admin (tenant sahibi/admin rolü)
  const admin = await db.user.findFirst({
    where: { tenantId: user!.tenantId, role: { in: ['admin', 'superadmin'] }, status: 'aktif' },
    orderBy: { createdAt: 'asc' },
  })

  let emailed = 0
  let tasksCreated = 0
  const emailErrors: string[] = []

  for (const sub of expiring) {
    const daysLeft = Math.max(0, Math.ceil((sub.expiryDate.getTime() - now.getTime()) / 86400000))
    const pkgName = sub.package.name
    const remaining = Math.max(0, sub.sessionsTotal - sub.sessionsUsed)

    // 1) Takip görevi
    try {
      await db.task.create({
        data: {
          tenantId: user!.tenantId,
          title: `Üyelik ${daysLeft} gün içinde bitiyor: ${sub.customerName} — ${pkgName}`,
          description: `${pkgName} paketi ${sub.sessionsTotal} seanslık; kalan seans: ${remaining}. Bitiş: ${sub.expiryDate.toLocaleDateString('tr-TR')}. Yenileme teklifi için müşteriyi arayın.`,
          dueDate: sub.expiryDate,
          assigneeId: admin?.id ?? null,
          priority: daysLeft <= 1 ? 'yuksek' : 'orta',
          autoGenerated: true,
        },
      })
      tasksCreated++
    } catch {
      // görev oluşturulamazsa hatırlatmayı bloklamaz
    }

    // 2) E-posta (bağlı müşterinin e-postası varsa)
    if (sub.customerId) {
      const apptCustomer = await db.appointmentCustomer.findUnique({
        where: { id: sub.customerId },
        select: { email: true, name: true },
      })
      if (apptCustomer?.email) {
        try {
          await sendMail({
            tenantId: user!.tenantId,
            to: apptCustomer.email,
            subject: `${pkgName} üyeliğiniz ${daysLeft} gün içinde bitiyor`,
            html: `<div style="font-family:Arial,sans-serif;max-width:520px">
  <h2 style="color:#059669;margin-bottom:8px;">Üyelik Hatırlatması</h2>
  <p>Merhaba <b>${apptCustomer.name || sub.customerName}</b>,</p>
  <p><b>${pkgName}</b> üyeliğiniz <b>${daysLeft} gün</b> içinde sona eriyor.</p>
  <ul>
    <li>Bitiş tarihi: <b>${sub.expiryDate.toLocaleDateString('tr-TR')}</b></li>
    <li>Kalan seans: <b>${remaining} / ${sub.sessionsTotal}</b></li>
  </ul>
  <p>Yenilemek için bizimle iletişime geçin; devam eden seanslarınızı aksatmayın.</p>
</div>`,
            text: `${pkgName} üyeliğiniz ${daysLeft} gün içinde bitiyor. Kalan seans: ${remaining}/${sub.sessionsTotal}. Yenilemek için bizimle iletişime geçin.`,
          })
          emailed++
        } catch (e) {
          emailErrors.push(e instanceof Error ? e.message : 'e-posta hatası')
        }
      }
    }

    await db.memberPackage.update({ where: { id: sub.id }, data: { remindedAt: new Date() } })
  }

  return ok({
    scanned: expiring.length,
    reminded: expiring.length,
    emailed,
    tasksCreated,
    emailErrors: emailErrors.slice(0, 3),
    days,
  })
}
